const data = {
  products: [
    {
      _iid: "12",
      name: " Slim Dress",
      category: "Dress",
      image: "/images/Dress.png",
      rating: 0.5,
      review: 10,
      price: 20,
      description: " ddsp1",
      countOnStock: 0,
    },
    {
      _iid: "22",
      name: " Slim Dress",
      category: "Dress",
      image: "/images/Dress.png",
      rating: 2,
      review: 100,
      price: 26,
      description: " Dsp2",
      countOnStock: 10,
    },
    {
      _iid: "32",
      name: " Slim Dress",
      category: "Dress",
      image: "/images/Dress.png",
      rating: 5,
      review: 50,
      price: 80,
      description: " dsp3",
      countOnStock: 200,
    },
    {
      _iid: "42",
      name: " Slim Dress",
      category: "Dress",
      image: "/images/Dress.png",
      rating: 4,
      review: 20,
      price: 300,
      description: " dsp4",
      countOnStock: 40,
    },
    {
      _iid: "25",
      name: " Slim Dress",
      category: "Dress",
      image: "/images/Dress.png",
      rating: 1.5,
      review: 18,
      price: 180,
      description: " dsp5",
      countOnStock: 26,
    },
    {
      _iid: "62",
      name: " Slim Dress",
      category: "Dress",
      image: "/images/Dress.png",
      rating: 3.5,
      review: 8,
      price: 98,
      description: "dsp6",
      countOnStock: 70,
    },
  ],
};

export default data;
